import { Link } from 'react-router-dom';

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using the App Hub ("the Platform"), you agree to be bound by this End User Licence Agreement ("Agreement"). If you do not agree to these terms, do not use the Platform.',
  },
  {
    title: '2. Licence Grant',
    body: 'You are granted a non-exclusive, non-transferable, revocable licence to access and use the tools and applications made available through the Platform solely for your internal business operations. This licence does not include the right to sublicense, resell, or redistribute any part of the Platform.',
  },
  {
    title: '3. Permitted Use',
    body: 'The Platform and its tools are intended for use by maritime, commercial diving, and related marine industry professionals. You agree to use the Platform only for lawful purposes and in accordance with this Agreement. You must not use the Platform in any way that could damage, disable, overburden, or impair it, or interfere with other users\u2019 access.',
  },
  {
    title: '4. Third-Party and User-Created Applications',
    body: 'The Platform may host or provide access to applications created by third parties or by users of the Platform ("Third-Party Apps"). The Platform operator makes no representations, warranties, or guarantees of any kind regarding Third-Party Apps, including but not limited to their accuracy, fitness for purpose, safety, legality, or reliability. The Platform operator accepts no responsibility or liability whatsoever for any Third-Party App, or for any loss, damage, injury, or consequence arising from your access to or use of any Third-Party App. Use of any Third-Party App is entirely at your own risk. The presence of a Third-Party App on the Platform does not constitute endorsement of that app or its developer.',
  },
  {
    title: '5. Fair Use',
    body: 'Where AI-powered features are included (such as document generation tools), access is subject to reasonable fair use limits. The Platform operator reserves the right to apply usage thresholds or rate limiting to AI-powered features where usage is excessive or automated. Normal professional use will not be affected.',
  },
  {
    title: '6. Subscription and Payment',
    body: 'Access to the Platform is provided on a subscription basis at the current published rate. Subscriptions are billed monthly or annually as selected at time of purchase. All fees are in Australian Dollars (AUD) and are exclusive of GST unless stated otherwise. Pricing may be updated with 30 days\u2019 written notice to existing subscribers.',
  },
  {
    title: '7. Intellectual Property',
    body: 'All software, tools, designs, content, and underlying technology on the Platform are the intellectual property of the Platform operator or its licensors. Nothing in this Agreement transfers any ownership rights to you. Output generated by AI-powered tools using your inputs may be used by you freely for your business purposes, however no warranty is made regarding the accuracy or fitness for purpose of any generated content.',
  },
  {
    title: '8. Disclaimer of Warranties',
    body: 'The Platform is provided "as is" and "as available." No warranties, express or implied, are made regarding the accuracy, reliability, or fitness for a particular purpose of any tool or output. Tools such as dive tables, quote calculators, and safety documents are provided as decision-support aids only and must not replace professional judgement, competent authority review, or applicable statutory obligations.',
  },
  {
    title: '9. Limitation of Liability',
    body: 'To the maximum extent permitted by applicable law, total liability for any claim arising out of or relating to this Agreement or the Platform shall not exceed the total fees paid by you in the 3 months preceding the claim. No liability is accepted for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunity. This limitation applies equally to claims arising from use of any application hosted on or accessible through the Platform, regardless of who created or published that application.',
  },
  {
    title: '10. Safety-Critical Notice',
    body: 'Certain tools on the Platform (including dive tables and decompression references) are provided for general reference only. Users are solely responsible for verifying that any information or output used in dive planning, safety management, or operational decisions complies with applicable regulations, organisational procedures, and the requirements of the relevant competent authority. No liability is accepted for decisions made on the basis of Platform outputs.',
  },
  {
    title: '11. Data and Privacy',
    body: 'User data is collected and processed in accordance with the Platform Privacy Policy. By using the Platform, you consent to this collection and processing. User data is not sold to third parties.',
  },
  {
    title: '12. Termination',
    body: 'Access to the Platform may be suspended or terminated at any time if you breach this Agreement or use the Platform in a manner reasonably considered harmful. You may cancel your subscription at any time; access will continue until the end of the current billing period.',
  },
  {
    title: '13. Governing Law',
    body: 'This Agreement is governed by the laws of Western Australia, Australia. Any disputes arising under this Agreement shall be subject to the exclusive jurisdiction of the courts of Western Australia.',
  },
  {
    title: '14. Amendments',
    body: 'This Agreement may be updated from time to time. Continued use of the Platform after notice of an updated Agreement constitutes acceptance of the revised terms.',
  },
];

export default function EUAPage() {
  return (
    <div className="eua-page">
      <div className="page-header">
        <h1>End User Licence Agreement</h1>
      </div>

      <div className="eua-container card">
        <p className="eua-updated">Last updated: April 2026</p>

        {sections.map(s => (
          <section key={s.title} className="eua-section">
            <h3 className="eua-section-title">{s.title}</h3>
            <p className="eua-section-body">{s.body}</p>
          </section>
        ))}
      </div>

      <div className="eua-back">
        <Link to="/" className="btn btn-secondary">Back to Dashboard</Link>
      </div>
    </div>
  );
}
